# 汽车轮毂字母识别系统 - 默认配置文件

# 预处理配置
preprocessing:
  enable: true
  # 亮度对比度调整
  brightness_contrast:
    enable: true
    clip_limit: 3.0
    tile_size: [4, 4]
  # 去噪处理
  denoise:
    enable: true
    method: "bilateral"  # gaussian, median, bilateral
    kernel_size: 5
    sigma: 1.5
  # 边缘增强
  edge_enhancement:
    enable: true
    method: "laplacian"  # sobel, laplacian
    kernel_size: 3
  # 二值化
  binarization:
    enable: false
    method: "otsu"  # adaptive, otsu
    block_size: 11
    c_value: 2
  # 形态学处理
  morphology:
    enable: true
    operation: "close"  # dilate, erode, open, close
    kernel_size: [3, 3]

# 文字检测配置
detection:
  engine: "paddleocr"  # paddleocr
  paddleocr:
    det_db_thresh: 0.1  # 降低检测阈值,提高敏感度(原0.2)
    det_db_box_thresh: 0.2  # 降低框阈值(原0.25)
    det_db_unclip_ratio: 2.0  # 增大展开比例,更容易检测到小文字(原1.6)
    max_side_len: 960
    use_dilation: false

# 文字识别配置
recognition:
  engine: "paddleocr"  # paddleocr, easyocr, auto
  paddleocr:
    rec_algorithm: "SVTR_LCNet"
    rec_batch_num: 6
    rec_image_shape: [3, 48, 320]
    max_text_length: 25
    lang: "en"
  easyocr:
    lang_list: ["en"]
    decoder: "beamsearch"
    beam_width: 5
    batch_size: 1
    allowlist: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+-×/. "
    paragraph: false
  
  # 云端OCR配置
  cloud_ocr:
    enabled: false  # 启用云OCR作为备用引擎
    provider: "aliyun"  # aliyun, tencent, baidu
    
    # 智能切换策略
    use_as_fallback: true  # 作为本地OCR的备用方案
    fallback_confidence_threshold: 0.7  # 低于此置信度时使用云OCR
    fallback_min_results: 2  # 本地识别结果少于此数量时使用云OCR
    
    # 阿里云配置 (请填写您的密钥)
    aliyun:
      access_key_id: "xxx"  # 请替换为您的AccessKey ID
      access_key_secret: "xxxx"  # 请替换为您的AccessKey Secret
      endpoint: "ocr-api.cn-hangzhou.aliyuncs.com"
      min_size: 8  # 最小字号

# 后处理配置
postprocessing:
  # 置信度过滤
  min_confidence: 0.4  # 降低置信度阈值,避免过滤正确结果(原0.6)
  # 长度过滤
  min_length: 1
  max_length: 30
  # 字符类型过滤
  enable_char_filter: true
  allowed_chars: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  # 区域过滤(过滤贴纸、标签等非轮毂文字)
  enable_region_filter: false  # 禁用区域过滤(效果不理想)
  min_area_ratio: 0.0003      # 最小面积比例(过滤过小噪点)
  max_area_ratio: 0.012       # 最大面积比例(降低阈值,更严格过滤大标签)
  min_aspect_ratio: 0.3        # 最小宽高比
  max_aspect_ratio: 8          # 最大宽高比
  center_region_only: false    # 是否只保留中心区域(可设为true过滤边缘文字)
  center_region_ratio: 0.7     # 中心区域比例
  # 相似字符纠正
  enable_correction: true
  correction_rules:
    - ["O", "0"]  # O与0
    - ["I", "1", "l"]  # I, 1, l
    - ["S", "5"]  # S与5
    - ["Z", "2"]  # Z与2
    - ["B", "8"]  # B与8
  # 结果去重
  enable_deduplication: true
  similarity_threshold: 0.9
  min_results: 4

# 多角度融合配置
multi_angle:
  fusion_method: "voting"  # voting, weighted, smart, merge
  min_images: 2
  max_images: 10
  alignment_method: "hybrid"  # position, content, semantic, hybrid
  return_alternatives: true
  alternative_threshold: 0.85

# 系统配置
system:
  use_gpu: false
  gpu_id: 0
  num_workers: 4
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  model_cache_dir: "./models"
  temp_dir: "./temp"
  output_dir: "./output"

# 可视化配置
visualization:
  enable: true
  draw_bbox: true
  draw_text: true
  draw_confidence: true
  bbox_color: [0, 255, 0]  # BGR格式
  text_color: [255, 0, 0]
  font_scale: 0.6
  thickness: 2
